### ISSUE TITLE
Youtube Ads

### ISSUE THREAD

**Issue by MrDavidson740** [theheroGAC/TubeVita#3]
I'm having an issue when youtube ads come up it only plays the ad then tries restarting the ad instead of playing the video.

**Comment by theheroGAC** [comment]
Please test this version https://github.com/theheroGAC/TubeVita/releases/tag/1.05

**Comment by theheroGAC** [comment]
new version https://github.com/theheroGAC/TubeVita/releases/download/1.07/Tubevita.vpk
